### PR TITLE
nicely formatted recipes with ASCII art

### LINKED ISSUE #122: Improved recipe formatting
**Is your feature request related to a problem? Please describe.**
It is difficult to easily read the crafting recipes in the info panel, and determine how the item can be used. For example the `log` can be used as an input and an output, but this is not immediately clear from the current recipe display. Additionally, it appears there is a furnace that can be used for crafting, and it is awkward to have it be listed on both the input and output sides.

**Describe the solution you'd like**
A clear and concise format for displaying recipes using ascii graphics, showing the input and count on the left, the crafting space above, and the output items and count on the right, with the item being inspected highlighted, as shown here:

Screen Shot 2021-09-30 at 12 15 11 PM

### PR DESCRIPTION
**Pull request by byorgey**
Draw nicely formatted recipes using ASCII art, showing inputs on the left, outputs on the right, and any other required entities at the top, and with the focused entity highlighted in one color, and missing or insufficient ingredients highlighted in a different color.  Thanks to Mark Goadrich for the idea!

Closes #122 .

### CODE REVIEW

**Comment by byorgey** [comment]
Here's a screenshot showing what it looks like now:

2021-09-19-162726_956x525_scrot

**Comment by byorgey** [comment]
Here's a screenshot showing what it looks like now:

recipes

**Comment by byorgey** [comment]
Just realized I should update the tutorial to match before merging this.

**Review by TristanCacqueray — APPROVED** [review]
This is lovely!

**Comment by byorgey** [comment]
Thanks! I will merge once I get a chance to update the tutorial.

**Pull request merged**
