### PR TITLE
Add entity growth rates and parameterize the `seedProgram`

### LINKED ISSUE #23: Parametrized growth rates
Entities which have the `growable` property, when harvested via the `grab` command, spawn a system robot representing a "seed", which takes a while to grow through two phases and then replaces itself with another copy of the originally harvested entity.  However, the length of time that it takes to grow is hard-coded into the program for the seed robot.  This should be configurable, by specifying some data in `entities.yaml`.

There are a lot more details yet to work out here; just putting this issue here as a placeholder for now.

### PR DESCRIPTION
**Pull request by byorgey**
* Add antiquoted int variables to the term AST, for including them in quasiquotes
* Add a `Maybe GrowthRate` field to `Entity`, which optionally records the min and max time an entity should take for each regrowth stage
* Make up some growth times for existing growable entities (very open to arguments that these should be higher or lower etc.)
* Parameterize the `seedProgram` on the growth rate

Closes #23 .

### CODE REVIEW

**Review by TristanCacqueray — APPROVED** [review]
The default growth times look good to me.

**Comment by TristanCacqueray** [comment]
It seems like the mergify configuration worked as expected: the commits got squashed using the PR comment as commit message, and rebased without a merge commit.

**Comment by byorgey** [comment]
Yep, looks good, though actually I think the commit message is the concatenation of the commit messages from the squashed commits?

**Comment by TristanCacqueray** [comment]
Oh you are right, I though the default would be to use the PR title+body. To get that we need to set `commit_message: title+body` in the merge configuration.

**Comment by byorgey** [comment]
> To get that we need to set `commit_message: title+body` in the merge configuration.

I think that probably makes more sense, since the titles of some of the individual commits may not be sensible to include.  We just have to make sure that the PR body contains a good description for the squashed commit.

**Pull request merged**
