### PR TITLE
Abstract Const commands out of reserved words list

### PR DESCRIPTION
**Pull request by 7h3w1zz**
Now that `constInfo` provides the name of Const values, there is no
need to re-list each command in the reserved words list.  Also
represent reserved words as Text instead of String.

### CODE REVIEW

**Comment by 7h3w1zz** [comment]
Talked about in #138

**Comment by byorgey** [comment]
Looks great.  While we're at it, can we also autogenerate the list of direction names, via `map show [minBound .. maxBound :: Direction]` or something like that?

I wonder if there is a way we could also autogenerate the names of types like `bool`, `int`, and so on...

**Comment by 7h3w1zz** [comment]
The directions in the reserved list could be abstracted in a similar way.  Either by using the pretty print code or by creating another function similar to `constInfo`.  The other term-level constructs (`def`, `let ... in ...`, etc.) would be more difficult to do.

**Comment by byorgey** [comment]
Oh, right, we can't use `show` for `Direction` since the names of the constructors don't match the syntax.  Huh, maybe it does make sense to make a function similar to `constInfo`.  It could contain the syntax and also the info needed for `toDirection`, `fromDirection`, and `applyTurn`.  Then we could rewrite the parser and pretty printer to make use of that info, so if we ever add any new `Direction` values we only have to add them in one place.  But I think this is getting to be a bigger change than I thought.  I'll just merge this as-is, and make a separate issue for the `Direction` stuff.

**Review by byorgey — APPROVED** [review]

**Comment by xsebek** [comment]
Thanks, @7h3w1zz, for finishing this after me. :+1:  (Sorry that I left it there, some TH error made me think it's untouchable.)

**Pull request merged**
