### PR TITLE
add flake.nix

### PR DESCRIPTION
**Pull request by wizzup**
using flake template from https://input-output-hk.github.io/haskell.nix/tutorials/getting-started-flakes/

I am using this for myself for a couple days and it working fine.
BTW, I don't know any other template that simpler than this. This one may seem overkill.

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
Thank you, that seems to work as expected, in particular nix build uses the correct hsnoise version.

Though I'm not sure the maintainers are ready to support another build system, could we have an extra CI job to prevent regression?

**Comment by byorgey** [comment]
Hi, thanks for the contribution!  On the one hand, as @TristanCacqueray says, I don't want to have another thing to support at this point.  I don't really understand how this works (why does it need `cardano-shell`? why are there multiple things called `ghc`, and with different versions than what we are testing on?), nor do I really want to put in the time to do so.  Having it live in the repo implicitly promises some level of official support that I don't want to be responsible for.

On the other hand I definitely see the value in providing this for people who want to use it. What if we put the instructions on how to set this up in the project wiki, and link to that from the README?

**Comment by TristanCacqueray** [comment]
If I understand correctly, nix flakes need to be part of the project to be useful, but without CI (and associated cache) this will eventually bitrot. Moreover it seems like flake.lock are still experimental and the one that is proposed definitely contains unrelated dependencies.

**Comment by byorgey** [comment]
OK, I am going to close this, but feel free to post this info about how to set it up somewhere (such as on the [swarm wiki](https://github.com/byorgey/swarm/wiki)---which I have now enabled and set to be editable by anyone---or elsewhere), and we will be happy to link to it from the README.

**Pull request closed without merging**
